### ISSUE TITLE
EL6 repo returning 404s

### ISSUE THREAD

**Issue by tbindervitti** [Graylog2/fpm-recipes#12] opened 2014-10-10 20:55 UTC
I'm attempting to install from the rpm repo on Amazon Linux, and I'm getting the following error:

yum search graylog
Loaded plugins: priorities, update-motd, upgrade-helper
https://packages.graylog2.org/repo/el/latest/0.90/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.

 One of the configured repositories failed (graylog2),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable graylog2

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=graylog2.skip_if_unavailable=true

failure: repodata/repomd.xml from graylog2: [Errno 256] No more mirrors to try.

It looks like everything at packages.graylog2.org is returning a 404 rather than providing repo information.

**Comment by pgehres** [comment] 2015-01-08 00:40
This isn't just an Amazon Linux issue. My stock CentOS 6.5 install has $releasever set to 6.5 which causes problems as well.

**Comment by bernd** [comment] 2016-04-14 08:27
Closing this because we cannot reproduce it and it seems to work for others as well. Please re-open if you still have problems with this. Thank you!

**Closed by bernd** 2016-04-14 08:27 UTC
