### ISSUE TITLE
CentOS 6 RPMs

### ISSUE THREAD

**Issue by ss44** [Graylog2/fpm-recipes#35] opened 2015-05-20 21:48 UTC
When following the steps here:  http://docs.graylog.org/en/latest/pages/installation.html#centos-6,
for CentOS6 (AWS Linux) running,

```
sudo yum install graylog-server graylog-web
```

returns the following:

```
https://packages.graylog2.org/repo/el/latest/1.0/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.


 One of the configured repositories failed (graylog),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable graylog

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=graylog.skip_if_unavailable=true

failure: repodata/repomd.xml from graylog: [Errno 256] No more mirrors to try.
```

**Comment by joschi** [comment] 2015-05-21 07:45
This is a duplicate of #12.

Please refer to https://github.com/Graylog2/fpm-recipes/issues/12#issuecomment-58746327 for a workaround on AWS Linux.

**Closed by joschi** 2015-05-21 07:45 UTC
