### ISSUE TITLE
Centos 7 Installation Failure

### ISSUE THREAD

**Issue by gvenka008c** [Graylog2/fpm-recipes#51] opened 2015-10-28 16:23 UTC
Hi Team,

I followed the below instructions to install on CentOS 7.
http://docs.graylog.org/en/1.1/pages/installation/operating_system_packages.html#centos-7

I am not able to start both the graylog-server and graylog-web service.
$ sudo systemctl start graylog-server
$ sudo systemctl start graylog-web

Error is as below:
/var/log/graylog-server/server.log
2015-10-28T16:18:51.413Z ERROR [CmdLineTool] Validating configuration file failed - exiting.
2015-10-28T16:19:01.942Z INFO  [CmdLineTool] Loaded plugins: [Anonymous Usage Statistics 1.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]]
2015-10-28T16:19:01.993Z ERROR [Server] No password secret set. Please define "password_secret" in your Graylog configuration.

Error from /var/log/messages
Oct 28 16:21:18 testmesosmas-cmce-01 systemd: Starting Graylog server...
Oct 28 16:21:18 testmesosmas-cmce-01 systemd: Started Graylog server.
Oct 28 16:21:18 testmesosmas-cmce-01 graylog-server: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Oct 28 16:21:18 testmesosmas-cmce-01 graylog-server: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Oct 28 16:21:19 testmesosmas-cmce-01 systemd: graylog-server.service: main process exited, code=exited, status=1/FAILURE
Oct 28 16:21:19 testmesosmas-cmce-01 systemd: Unit graylog-server.service entered failed state.
Oct 28 16:21:22 testmesosmas-cmce-01 systemd: graylog-web.service holdoff time over, scheduling restart.
Oct 28 16:21:22 testmesosmas-cmce-01 systemd: Stopping Graylog web interface...
Oct 28 16:21:22 testmesosmas-cmce-01 systemd: Starting Graylog web interface...
Oct 28 16:21:22 testmesosmas-cmce-01 systemd: Started Graylog web interface.
Oct 28 16:21:23 testmesosmas-cmce-01 graylog-web: Play server process ID is 16589
ct 28 16:23:17 testmesosmas-cmce-01 graylog-web: Play server process ID is 17513
Oct 28 16:23:18 testmesosmas-cmce-01 graylog-web: Oops, cannot start the server.
Oct 28 16:23:18 testmesosmas-cmce-01 graylog-web: java.lang.IllegalStateException: No application.secret configured.
Oct 28 16:23:18 testmesosmas-cmce-01 graylog-web: at lib.Global.onStart(Global.java:108)

Let me know if any details required. Thanks.

Thanks,
Govind

**Comment by gvenka008c** [comment] 2015-10-28 16:29
Adding Server details
[graylog-server]# uname -a
Linux testmesosmas-cmce-01.sys.comcast.net 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joschi** [comment] 2015-10-28 16:51
> ```
2015-10-28T16:19:01.993Z ERROR [Server] No password secret set. Please define "password_secret" in your Graylog configuration.
```

I think you should define `password_secrect` (https://github.com/Graylog2/graylog2-server/blob/1.2.2/misc/graylog2.conf#L9-L11) in your configuration file. :wink:

**Comment by bernd** [comment] 2015-11-11 14:21
Closing this, not a bug but a missing configuration option.

**Closed by bernd** 2015-11-11 14:21 UTC

**Comment by DCentos** [comment] 2018-11-22 10:46
Actually i have the same problem, i am installing graylog on a cloud environment, i have the server.conf defined correctly with the IPs, etc Graylog, elasticsearch and mongo are all started and executing, but still no Web Interface, i have already tried to change the port to 12900 on the REST API but nothing, in the logs i see this:

2018-11-22T04:30:57.719-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
2018-11-22T04:30:57.719-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
2018-11-22T04:30:57.719-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
2018-11-22T04:30:57.720-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
2018-11-22T04:30:57.720-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
2018-11-22T04:30:57.720-06:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.RuntimeException: kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.

Please help, thanks
