### ISSUE TITLE
Debian wheezy 32  bits

### ISSUE THREAD

**Issue by andarius40** [Graylog2/fpm-recipes#30] opened 2015-03-14 16:29 UTC
When I install graylog-1.0-repository-debian7_latest.deb, on the file
/etc/apt/sources.list.d/graylog.list
- I have deb https://packages.graylog2.org/repo/debian wheezy 1.0
     but depot is
      https://packages.graylog2.org/debian wheezy 1.0
- and when i update package,I have the message
       not possible to download https://packages.graylog2.org/debian/dists/wheezy/1.0/binayr-i386/Packages
        the request URL returned error 403

**Comment by joschi** [comment] 2015-03-14 19:16
The correct URL to the i386 repository for Debian Wheezy is https://packages.graylog2.org/debian/dists/wheezy/1.0/binary-i386 (there's a typo in the URL you've mentioned).

**Comment by andarius40** [comment] 2015-03-20 17:18
On the file /etc/apt/sources.list.d/graylog.list, I have

deb https://packages.graylog2.org/debian wheezy 1.0

It's correct ?

When I update package, I have message 
the message not possible to download https://packages.graylog2.org/debian/dists/wheezy/1.0/binayr-i386/Packages the request URL returned error 403

**Comment by joschi** [comment] 2015-03-21 23:19
The file `/etc/apt/sources.list.d/graylog.list` should contain the line
```
deb https://packages.graylog2.org/repo/debian wheezy 1.0
```
(see https://github.com/Graylog2/fpm-recipes/blob/4a4e59d59e45cde73d69110eb97f3399da92d981/recipes/graylog-repository/recipe.rb#L40).

Unfortunately I cannot reproduce the problem you've described and the URL with typo ("binayr-i386" instead of "binary-i386") doesn't appear anywhere in our repositories.

Please purge the repository package "graylog-1.0-repository-debian7" from your system and remove the file from `/etc/apt/sources.list.d/`. After that please reinstall the Graylog repository descriptors as described in http://docs.graylog.org/en/1.0/pages/installation.html#debian-7

**Comment by bernd** [comment] 2015-05-20 09:09
Closing this, please re-open if you still have problems.

**Closed by bernd** 2015-05-20 09:09 UTC
